### ISSUE TITLE
Install / Upgrade issue in v0.0.4

### ISSUE THREAD

**Issue by Lilogan** [dim00z/RacksDirections#1]
**Describe the Issue**
During upgrade from v0.0.2 to v0.0.4, when you click on upgrade, nothing append
In apache2 error log :
`PHP Warning:  include_once(/inc/RacksDirections.class.php): Failed to open stream: No such file or directory in /var/www/html/glpi/plugins/racksdirections/setup.php on line 100`

**Version(s) Affected**
0.0.4

**Possible Solution**
Rename `inc/racksdirections.class.php` to `inc/RacksDirections.class.php`

**Comment by d1m007** [comment]
Fixed, thanks.
